### PR TITLE
Add static generation strategy

### PR DESCRIPTION
**Pull request by cschindl**
First of all, thanks for this great package.

I am in the process of creating a [middleware](https://github.com/cschindl/php-openapi-mock-middleware) that simulates the API responses using an OpenAPI schema. For this it is important that the responses are generated statically or based on fixed sample data.

While searching for a suitable package I found this one, which fits great but only generates dynamic data.

In my daily work I use [Prism](https://stoplight.io/open-source/prism) to generate fake data for existing and new API endpoints. The advantage is that I can define new endpoints using the OpenApi schema and this data is immediately available to the frontend, so that development can already start even though the functionality has not yet been created in the backend.

Unfortunately there is no direct integration of Prism as a PHP library so I am always forced to run Prism via Docker. With the new middleware I could generate the simulated API responses directly from my PHP project which would simplify development and deployment.

For this reason, I added an optional option to generate static fake data. This will generate the data the same way [Prism](https://docs.stoplight.io/docs/prism/83dbbd75532cf-http-mocking#static-or-dynamic-generation) would generate it.

```php
use Vural\OpenAPIFaker\Options;

$faker = \Vural\OpenAPIFaker\OpenAPIFaker::createFromJson($yourSchemaAsJson)
    ->setOptions(['strategy' => Options::STRATEGY_STATIC]);

// generate static fake data
// @see https://github.com/cschindl/php-openapi-faker/blob/master/tests/Integration/OpenAPIFakerTest.php#L503
$fakeData = $faker->mockResponse('/todos', 'GET');

// generate static fake date for a given example
// @see https://github.com/cschindl/php-openapi-faker/blob/master/tests/Integration/OpenAPIFakerTest.php#L530
$fakeData = $faker->mockResponseForExample('/todos', 'GET', 'otherExample');

```

### CODE REVIEW

**Comment by canvural** [comment]
Wow, this is huge! 😮 

Thank you for your kind words! 😊 

The idea seems great! Generating repeatable data sure would be useful. 

I'll try to review this next week.

**Comment by canvural** [comment]
This looks really good! I have some tiny nitpicks but I'm gonna merge it now and clean them up later! So probably this week I can make a new release with this.

Thank you again! This will definitely be useful!

**Comment by cschindl** [comment]
That sounds great. Thanks a lot! I'll be happy to follow your adjustments as I'm very interested in improving and even tiny nitpicks where I can improve are of great interest to me.

**Comment by canvural** [comment]
@cschindl Released this as 2.1.0 https://github.com/canvural/php-openapi-faker/releases/tag/2.1.0, https://twitter.com/can__vural/status/1595017672995278848

Thanks again for this!

**Pull request merged**
